AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    slack-unfurling-esa
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 30

Parameters:
    EsaAccessToken:
        Type: String
        Default: your-token
    SlackOauthAccessToken:
        Type: String
        Default: your-slack-oauth-token

Resources:

    SlackUnfrulingEsaFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: slack-unfurling-esa/
            Handler: app.lambda_handler
            Runtime: ruby3.3
            Environment:
                Variables:
                    ESA_ACCESS_TOKEN: !Ref EsaAccessToken
                    SLACK_OAUTH_ACCESS_TOKEN: !Ref SlackOauthAccessToken
            MemorySize: 128
            Events:
                SlackUnfrulingEsa:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /call
                        Method: post

Outputs:

    SlackUnfrulingEsaApi:
      Description: "API Gateway endpoint URL for Prod stage for Slack Unfurling Esa function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/call/"

    SlackUnfrulingEsaFunction:
      Description: "Slack Unfurling Esa Lambda Function ARN"
      Value: !GetAtt SlackUnfrulingEsaFunction.Arn

    SlackUnfrulingEsaFunctionIamRole:
      Description: "Implicit IAM Role created for Slack Unfurling Esa function"
      Value: !GetAtt SlackUnfrulingEsaFunctionRole.Arn
